<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	  <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Program Files (x86)\steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
	  <Reference Include="0Harmony">
		  <HintPath>C:\Program Files (x86)\steam\steamapps\common\Gorilla Tag\BepInEx\core\0Harmony.dll</HintPath>
	  </Reference>
    <Reference Include="BepInEx">
      <HintPath>C:\Program Files (x86)\steam\steamapps\common\Gorilla Tag\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Harmony">
      <HintPath>C:\Program Files (x86)\steam\steamapps\common\Gorilla Tag\BepInEx\core\BepInEx.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="PlayFab">
      <HintPath>C:\Program Files (x86)\steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\PlayFab.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Program Files (x86)\steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Program Files (x86)\steam\steamapps\common\Gorilla Tag\Gorilla Tag_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
